name: LogBack
version: '${project.version}'
main: vip.floatationdevice.msu.logback.LogBack
api-version: 1.13
authors: [ MCUmbrella ]
website: https://github.com/MCUmbrella
commands:
  logback:
    description: "Teleport to logout location"
